### ISSUE TITLE
switch (response.StatusCode) ERROR

### ISSUE THREAD

**Issue by benltz** [KeyAuth/KeyAuth-CSHARP-Example#31]
every time i try to start it i get an error

![Screenshot 2022-11-02 173254](https://user-images.githubusercontent.com/105741857/199547602-e36c64bb-95fb-4d27-babd-30fc9c5e7388.png)

**Comment by wnelson03** [comment]
It seems from your image that there was an SSL error. This could be because you're using a proxy or network debugger. If you are, make sure to disable that. Or, it could be because your internet provider has blocked the `keyauth.win` domain name. This is quite common due to the number of programs contacting that domain, a lot of which have high virus scanner scores due to obfuscation.

I recommend you use custom domains, tutorial video here https://www.youtube.com/watch?v=a2SROFJ0eYc

![image](https://user-images.githubusercontent.com/83034852/200761633-176e95b9-93f9-4438-a43a-419281989be4.png)
